package com.likeminds.feed.android.core.utils.base.model

import androidx.annotation.IntDef

const val ITEM_NONE = 0
const val ITEM_POST_TEXT_ONLY = 1
const val ITEM_POST_SINGLE_IMAGE = 2
const val ITEM_POST_SINGLE_VIDEO = 3
const val ITEM_POST_DOCUMENTS = 4
const val ITEM_POST_LINK = 5
const val ITEM_POST_MULTIPLE_MEDIA = 6
const val ITEM_MULTIPLE_MEDIA_IMAGE = 7
const val ITEM_MULTIPLE_MEDIA_VIDEO = 8
const val ITEM_POST_MEDIA = 9
const val ITEM_POST_ATTACHMENT = 10
const val ITEM_OVERFLOW_MENU_ITEM = 11
const val ITEM_POST_DOCUMENTS_ITEM = 12
const val ITEM_POST_CONTENT = 13
const val ITEM_USER = 14
const val ITEM_COMMENT = 15
const val ITEM_REPLY = 16
const val ITEM_NO_COMMENTS_FOUND = 17
const val ITEM_COMMENTS_COUNT = 18
const val ITEM_VIEW_MORE_REPLY = 19
const val ITEM_ACTIVITY_FEED = 20
const val ITEM_LIKES_SCREEN = 21
const val ITEM_REPORT_TAG = 22
const val ITEM_REASON_CHOOSE = 23
const val ITEM_TOPIC = 24
const val ITEM_ALL_TOPICS = 25

@IntDef(
    ITEM_NONE,
    ITEM_POST_TEXT_ONLY,
    ITEM_POST_SINGLE_IMAGE,
    ITEM_POST_SINGLE_VIDEO,
    ITEM_POST_DOCUMENTS,
    ITEM_POST_LINK,
    ITEM_POST_MULTIPLE_MEDIA,
    ITEM_MULTIPLE_MEDIA_IMAGE,
    ITEM_MULTIPLE_MEDIA_VIDEO,
    ITEM_POST_MEDIA,
    ITEM_POST_ATTACHMENT,
    ITEM_OVERFLOW_MENU_ITEM,
    ITEM_POST_DOCUMENTS_ITEM,
    ITEM_POST_CONTENT,
    ITEM_USER,
    ITEM_COMMENT,
    ITEM_REPLY,
    ITEM_NO_COMMENTS_FOUND,
    ITEM_COMMENTS_COUNT,
    ITEM_VIEW_MORE_REPLY,
    ITEM_ACTIVITY_FEED,
    ITEM_LIKES_SCREEN,
    ITEM_REPORT_TAG,
    ITEM_REASON_CHOOSE,
    ITEM_TOPIC,
    ITEM_ALL_TOPICS
)

@Retention(AnnotationRetention.SOURCE)
annotation class LMFeedViewType